### ISSUE TITLE
Select License and create licence file in the 3 repos

### ISSUE THREAD

**Issue by tdurieux** [tdurieux/rose6icse#7]

**Comment by tdurieux** [comment]
Which license do you want?

I generally go for MIT or Apache or GNU 3.

**Comment by jff** [comment]
I am happy with MIT license

**Comment by ruimaranhao** [comment]
I would go with the Apache License 2.0 (mainly because of the conditions in https://choosealicense.com/licenses/apache-2.0/). I've updated the file, let me know if you prefer another one by reopening this issue.

**Comment by tdurieux** [comment]
The license needs to be added to the 3 repos including this on https://github.com/smartbugs/smartbugs

**Comment by ruimaranhao** [comment]
added to https://github.com/smartbugs/smartbugs. which other one needs such a file?

**Comment by jff** [comment]
https://github.com/smartbugs/smartbugs-wild
https://github.com/smartbugs/smartbugs-results

**Comment by ruimaranhao** [comment]
All done.
